# -- Naldom Python Runtime --
# naldom_runtime.py

import random

# This file acts as the "standard library" for code generated by the Naldom compiler.
# It contains the implementations of the high-level functions that the IR-HL refers to.

def create_random_array(size: int) -> list:
    """Generates a list of `size` random integers between 0 and 100."""
    print(f"Runtime: Creating an array of {size} random numbers...")
    return [random.randint(0, 100) for _ in range(size)]

def sort_array(arr: list, order: str):
    """Sorts the given list in-place."""
    print(f"Runtime: Sorting the array in {order} order...")
    if order.lower() == "descending":
        arr.sort(reverse=True)
    else:
        arr.sort(reverse=False) # Default to ascending

def print_array(arr: list):
    """Prints the array to the console with a label."""
    print("\n--- Naldom Output ---")
    print(arr)
    print("---------------------\n")
    

# --- Generated Code ---
var_0 = create_random_array(10)
sort_array(var_0, 'ascending')
print_array(var_0)