[package]
name = "naldom-runtime"
version = "0.1.0"
edition = "2024"
# Inherits most fields from workspace.package
description = "Minimal cross-platform runtime for Naldom generated code."

[dependencies]
# Example: wasmtime = "19.0" # If WASM runtime is implemented directly
