[package]
name = "naldom-core"
# version = "0.1.0" # Inherited from workspace.package
# edition = "2021" # Inherited from workspace.package
# authors = ["The Naldom Project Contributors"] # Inherited
# license = "MIT" # Inherited
# repository = "https://github.com/naldom-lang/naldom-lang" # Inherited
description = "Core compiler components for Naldom: NLD Parser, IntentGraph, Semantic Analysis, Optimization, IR Code Generation."

[dependencies]
naldom-ir = { path = "../naldom-ir" } # Dependency on our common IR crate
# Other core dependencies will go here later
# Example: anyhow = { workspace = true } # Use workspace dependency if defined
