# .github/workflows/rust-ci.yml

name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install System Dependencies (Build Tools, LLVM 17)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y llvm-17-dev clang-17 libclang-17-dev libpolly-17-dev

      - name: Create llvm-config symlink
        run: sudo ln -s /usr/bin/llvm-config-17 /usr/bin/llvm-config

      - name: Set LLVM environment variables
        run: |
          LLVM_PATH=$(llvm-config-17 --prefix)
          echo "LLVM_PREFIX=$LLVM_PATH" >> $GITHUB_ENV
          echo "LLVM_SYS_170_PREFIX=$LLVM_PATH" >> $GITHUB_ENV

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --features naldom-core/mock-llm -- -D warnings

      - name: Build
        run: cargo build --verbose --features naldom-core/mock-llm

      - name: Run tests
        run: cargo test --all-targets --verbose --features naldom-core/mock-llm